import Ajv2020 from "ajv/dist/2020.js";
import addFormats from "ajv-formats";
import fc from "fast-check";
import { describe, expect, it } from "vitest";
import { defaultBackend, generateFromSchema } from "../src/index.js";
import { arbitrarySchema } from "./arbitrary-schema.js";

/**
 * Property-based test: for an arbitrary bounded JSON Schema `S` (the supported
 * node kinds, depth <= 3 — see arbitrary-schema.ts) and seed `s`, the value generated by the
 * walker validates against `S` per a real JSON Schema checker (Ajv, draft-2020-12) used as an
 * independent oracle — this is a stronger check than our own hand-written fixtures, since the
 * schemas are adversarially generated rather than hand-picked to be "nice."
 *
 * A second property checks determinism directly: the same schema + seed produces a deep-equal
 * value across two independent generation calls.
 *
 * Exercised directly against the walker (`generateFromSchema` + `defaultBackend`) rather than
 * through a specific vendor's Standard Schema, since the point is to stress the JSON-Schema-
 * to-value walker itself, independent of any vendor's JSON Schema conversion fidelity.
 */

const ajv = new Ajv2020({ allowUnionTypes: true, strict: false });
addFormats(ajv);

function generate(schema: Record<string, unknown>, seed: number): unknown {
  const backend = defaultBackend.create(seed);
  return generateFromSchema(schema, { backend, root: schema, maxDepth: 5, projection: "output" }, "", 0);
}

describe("property: generated values validate against their own schema (Ajv oracle)", () => {
  it("for arbitrary schema S and seed s, fake(S, {seed: s}) validates against S", () => {
    fc.assert(
      fc.property(arbitrarySchema(), fc.integer({ min: 0, max: 1_000_000 }), (schema, seed) => {
        const validate = ajv.compile(schema);
        let value: unknown;
        try {
          value = generate(schema, seed);
        } catch (error) {
          // A structurally-impossible `uniqueItems: true` + `minItems` combination (e.g. a
          // nested array of `const`-typed items, cardinality 1, with `minItems: 2`) is a
          // legitimate, deliberately-thrown, separately-tested outcome (unique-items.test.ts)
          // — not a walker defect this property is checking for. The unbounded arbitrary
          // generator can produce such combinations without "knowing" the item schema's
          // cardinality ahead of time; treat this specific documented error as a vacuous pass
          // for this trial rather than a failure. Any OTHER thrown error still fails the test.
          if (error instanceof Error && /could not generate \d+ unique items/.test(error.message)) {
            return true;
          }
          throw error;
        }
        const valid = validate(value);
        if (!valid) {
          throw new Error(
            `Schema: ${JSON.stringify(schema)}\nSeed: ${seed}\nValue: ${JSON.stringify(value)}\nErrors: ${JSON.stringify(validate.errors)}`,
          );
        }
        return valid;
      }),
      { numRuns: 100 },
    );
  });
});

describe("property: determinism (same seed twice -> deep equal)", () => {
  it("for arbitrary schema S and seed s, generating twice with the same seed produces deep-equal values", () => {
    fc.assert(
      fc.property(arbitrarySchema(), fc.integer({ min: 0, max: 1_000_000 }), (schema, seed) => {
        // A structurally-impossible uniqueItems case (see the sibling property test above)
        // throws deterministically both times -- that's still "the same outcome twice," but
        // there's nothing to deep-equal-compare, so just confirm both calls throw the same
        // documented error rather than one succeeding and one not.
        let a: { ok: true; value: unknown } | { ok: false; message: string };
        let b: typeof a;
        try {
          a = { ok: true, value: generate(schema, seed) };
        } catch (error) {
          a = { ok: false, message: error instanceof Error ? error.message : String(error) };
        }
        try {
          b = { ok: true, value: generate(schema, seed) };
        } catch (error) {
          b = { ok: false, message: error instanceof Error ? error.message : String(error) };
        }
        expect(a).toEqual(b);
        return true;
      }),
      { numRuns: 100 },
    );
  });
});
